[variables]
NIXPACKS_PYTHON_REQUIREMENTS_PATH = "server/requirements.txt"

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["pip install -r server/requirements.txt"]

[start]
cmd = "python server/server.py"

[build]
language = "python"
