[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = []

[phases.build]
cmds = []

[start]
cmd = "python3 server/server.py"

[variables]
NIXPACKS_PYTHON_REQUIREMENTS_PATH = "server/requirements.txt"
