[variables]
NIXPACKS_PYTHON_REQUIREMENTS_PATH = "server/requirements.txt"

[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = ["python3 -m pip install -r server/requirements.txt"]

[start]
cmd = "python3 server/server.py"
